repository:
  description: Sihnon server packages
  
  maintenance:
  #  clean_cache: 1
  
    remove:
      - net-misc/choria-bin
      - dev-ruby/puppetdb-termini
      - www-apps/cgit

build:
  script:
    pre:
      - eselect python set python3.6
      - eselect ruby set ruby24

  emerge:
    # Be consistent with sabayon mainline repositories
    profile: "default/linux/amd64/17.0/desktop"

    # Install each package separately
    split_install: 1
    preserved_rebuild: 1
    default_args: "--accept-properties=-interactive --quiet --oneshot --complete-graph --buildpkg --newuse"

  equo:
    repositories:
      - sihnon-common

    dependency_install:
      prune_virtuals: 1

    package:
      mask:
        - dev-db/mariadb-galera

  # Use ebuilds from the following layman overlays
  overlays:
    - ace
    - awesome
    - barzog-overlay
    - defiance
    - fkmclane
    - flavour
    - funtoo
    - gitlab
    - mrueg
    - pentoo
    - sihnon
    - raw

  # Packages to be built in this repo
  target:
    - dev-db/phpmyadmin
    - dev-qt/qtsql
    - net-analyzer/icinga
    - net-analyzer/icinga2
    - net-analyzer/icinga-web
    - net-dns/bind-dyndb-ldap
    - net-irc/quassel
    - net-misc/memcached::gentoo
    - net-nds/gssproxy::gentoo
    - net-nds/phpldapadmin::gentoo
    - net-p2p/deluge
    - net-wireless/eyefiserver::sihnon
    - net-wireless/unifi
    - www-apps/dokuwiki
    - www-apps/icingaweb2
    - www-apps/kibana-bin
    - www-apps/piwik
    - www-apps/wordpress
    - www-misc/shellinabox

# vim: set ts=2 shiftwidth=2 expandtab :

