repository:
   description: Pentesting repository
build:
  emerge:
    # Install each package separately
    split_install: 1
    features: assume-digests binpkg-logs compressdebug config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync news parallel-fetch preserve-libs protect-owned sandbox sfperms splitdebug strict unknown-features-warn unmerge-logs unmerge-orphans userfetch usersandbox usersync xattr userpriv
  overlays:
    - pentoo
  equo:
    package:
      install:
        - dev-ruby/timers:4
  target:
    - net-analyzer/dnsrecon::pentoo
    - net-analyzer/etherape::pentoo
    - net-analyzer/ipv6-toolkit::pentoo
    - net-analyzer/aimsniff::pentoo
    - app-fuzz/bss::pentoo
    - net-wireless/bt-audit::pentoo
    - net-wireless/crackle::pentoo
    - net-wireless/kismet-ubertooth::pentoo
    - app-exploits/weevely::pentoo
    - net-wireless/wifite::pentoo
    - net-analyzer/bettercap::LocalOverlay # from local overlay
    - dev-db/sqlmap::pentoo
    - net-proxy/zaproxy::pentoo
    - net-analyzer/sslyze::pentoo
    - net-analyzer/recon-ng::pentoo
    - net-wireless/cowpatty::pentoo
    - net-wireless/wifitap::pentoo
    - net-misc/tcpick::pentoo
    - app-antivirus/malheur::pentoo
    - app-crypt/steghide::pentoo
    - app-fuzz/dotdotpwn::pentoo
    - dev-util/radare2::pentoo
    - net-analyzer/inguma::pentoo
    - net-analyzer/w3af::pentoo
    - net-analyzer/yersinia::pentoo
    - www-apps/beef::pentoo
    - net-analyzer/set::pentoo
    - net-analyzer/armitage-bin::pentoo
    - app-forensics/inception::pentoo
    - app-cdr/dumpet::pentoo
    - app-crypt/SIPcrack::pentoo
    - app-crypt/asleap::pentoo
    - app-crypt/cpyrit_cuda::pentoo
    - app-crypt/hashkill::pentoo
    - app-crypt/oclhashcat-plus-bin::pentoo
    - app-crypt/pyrit::pentoo
    - app-crypt/rcracki_mt::pentoo
    - app-crypt/samdump2::pentoo
    - app-crypt/steghide::pentoo
    - app-dicts/raft-wordlists::pentoo
    - app-forensics/dff::pentoo
    - app-forensics/disitool::pentoo
    - app-forensics/libforensic1394::pentoo
    - app-forensics/libpff::pentoo
    - app-forensics/libvshadow::pentoo
    - app-forensics/make-pdf::pentoo
    - app-forensics/pdf-parser::pentoo
    - app-forensics/pdfid::pentoo
    - app-forensics/streams::pentoo
    - app-forensics/tcpxtract::pentoo
    - app-forensics/volatility::pentoo
    - app-forensics/yara::pentoo
    - app-forensics/yim2text::pentoo
    - app-fuzz/Peach::pentoo
    - app-fuzz/bed::pentoo
    - app-fuzz/bss::pentoo
    - app-fuzz/dotdotpwn::pentoo
    - app-fuzz/fuzzdb::pentoo
    - app-fuzz/fuzzer-server::pentoo
    - app-fuzz/http-fuzz::pentoo
    - app-fuzz/ohrwurm::pentoo
    - app-fuzz/slowhttptest::pentoo
    - app-fuzz/smtp-fuzz::pentoo
    - app-i18n/scim::pentoo
    - app-misc/crunch::pentoo
    - app-misc/ddate::pentoo
    - app-misc/dradis::pentoo
    - app-misc/libmsr::pentoo
    - dev-db/minimysqlator::pentoo
    - dev-db/mssqlscan::pentoo
    - dev-db/oat::pentoo
    - dev-db/sqlbf::pentoo
    - dev-db/sqlibf::pentoo
    - dev-db/sqlix::pentoo
    - dev-db/sqlmap::pentoo
    - dev-db/sqlsus::pentoo
    - dev-db/themole::pentoo
    - dev-util/apktool::pentoo
    - dev-util/ati-app-sdk-bin::pentoo
    - dev-util/bokken::pentoo
    - dev-util/capstone::pentoo
    - dev-util/dex2jar::pentoo
    - dev-util/radare2::pentoo
    - net-analyzer/arpantispoofer::pentoo
    - net-analyzer/bro::pentoo
    - net-analyzer/cisco-auditing-tool::pentoo
    - net-analyzer/cisco-bruteforce-enabler::pentoo
    - net-analyzer/cisco-scanner::pentoo
    - net-analyzer/cisco-torch::pentoo
    - net-analyzer/davtest::pentoo
    - net-analyzer/dnsa::pentoo
    - net-analyzer/dnsrecon::pentoo
    - net-analyzer/dnsenum::pentoo
    - net-analyzer/enum4linux::pentoo
    - net-analyzer/evilgrade::pentoo
    - net-analyzer/fierce::pentoo
    - net-analyzer/geoedge::pentoo
    - net-analyzer/geoipgen::pentoo
    - net-analyzer/httprint::pentoo
    - net-analyzer/hyenae::pentoo
    - net-analyzer/inguma::pentoo
    - net-analyzer/jmsdigger-bin::pentoo
    - net-analyzer/loki::pentoo
    - net-analyzer/maketh::pentoo
    - net-analyzer/masscan::pentoo
    - net-analyzer/nacker::pentoo
    - net-analyzer/netmap::pentoo
    - net-analyzer/nmap_vulscan::pentoo
    - net-analyzer/ntp-fingerprint::pentoo
    - net-analyzer/onesixtyone::pentoo
    - net-analyzer/padbuster::pentoo
    - net-analyzer/plecost::pentoo
    - net-analyzer/polenum::pentoo
    - net-analyzer/post-it-dos::pentoo
    - net-analyzer/ppscan::pentoo
    - net-analyzer/recon-ng::pentoo
    - net-analyzer/rpcapd::pentoo
    - net-analyzer/sessionlist::pentoo
    - net-analyzer/set::pentoo
    - net-analyzer/sipvicious::pentoo
    - net-analyzer/smtpmap::pentoo
    - net-analyzer/snmpenum::pentoo
    - net-analyzer/sqlninja::pentoo
    - net-analyzer/sslcat::pentoo
    - net-analyzer/sslscan::pentoo
    - net-analyzer/sslstrip::pentoo
    - net-analyzer/ssltest::pentoo
    - net-analyzer/subdomainer::pentoo
    - net-analyzer/suricata::pentoo
    - net-analyzer/thc-pptp-bruter::pentoo
    - net-analyzer/thc-ssl-dos::pentoo
    - net-analyzer/theHarvester::pentoo
    - net-analyzer/upnpwn::pentoo
    - net-analyzer/voiphopper::pentoo
    - net-analyzer/vomit::pentoo
    - net-analyzer/waffit::pentoo
    - net-analyzer/wapiti::pentoo
    - net-analyzer/w3af::pentoo
    - net-analyzer/webshag::pentoo
    - net-analyzer/wfuzz::pentoo
    - net-analyzer/wolpertinger::pentoo
    - net-analyzer/wpscan::pentoo
    - net-analyzer/xplico::pentoo
    - net-analyzer/zarp::pentoo
    - net-fs/afpfs-ng::pentoo
    - net-misc/bdfactory::pentoo
    - net-misc/brutessh::pentoo
    - net-misc/edgessh::pentoo
    - net-misc/f5vpn-login::pentoo
    - net-misc/faifa::pentoo
    - net-misc/fwknop::pentoo
    - net-misc/karma::pentoo
    - net-misc/rdesktop-brute::pentoo
    - net-misc/sipp::pentoo
    - net-misc/httpfs::pentoo
    - net-misc/sslh::pentoo
    - net-misc/t50::pentoo
    - net-misc/tcpick::pentoo
    - net-misc/voipong::pentoo
    - net-misc/wlan2eth::pentoo
    - net-proxy/3proxy::pentoo
    - net-proxy/burpsuite::pentoo
    - net-proxy/hosproxy::pentoo
    - net-proxy/mitmproxy::pentoo
    - net-proxy/pbounce::pentoo
    - net-proxy/proxystrike::pentoo
    - net-proxy/pwnat::pentoo
    - net-proxy/redsocks::pentoo
    - net-proxy/sshttp::pentoo
    - net-proxy/zaproxy::pentoo
    - net-wireless/bt-audit::pentoo
    - net-wireless/bully::pentoo
    - net-wireless/cowpatty::pentoo
    - net-wireless/fern-wifi-cracker::pentoo
    - net-wireless/grimwepa::pentoo
    - net-wireless/haraldscan::pentoo
    - net-wireless/horst::pentoo
    - net-wireless/karmetasploit::pentoo
    - net-wireless/killerbee::pentoo
    - net-wireless/mfoc::pentoo
    - net-wireless/morse2txt::pentoo
    - net-wireless/rfidtool::pentoo
    - net-wireless/virtualradar-bin::pentoo
    - net-wireless/wifite::pentoo
    - net-analyzer/whatweb::pentoo
    - net-analyzer/ike-scan::pentoo
    - net-analyzer/medusa::pentoo
    - net-analyzer/nikto::pentoo
    - net-analyzer/nmap_vulscan::pentoo

#    - net-wireless/btscanner::pentoo

