repository:
  description: Dotnet packages
#  maintenance:
#    clean_cache: 1

build:
  overlays:
    - dotnet
    - shnurise

  emerge:
    split_install: 1
    remote_overlay:
      - sabayon|git|https://github.com/Sabayon/for-gentoo.git

  # Packages to be built in this repo
  target:
    - 'dev-dotnet/mono-options'
    - 'dev-lang/mono'
    - 'dev-util/mono-packaging-tools'
    - 'dev-util/nunit'
    - 'dev-util/xunit'
    - 'app-shells/pash'
    - 'dev-util/monodevelop'
    - 'www-servers/xsp'
    - 'www-apache/mod_mono'
    - 'dev-dotnet/npgsql'
    - 'www-apps/orchard-cms'
    - 'dev-util/gplex-dbremner'
    - 'dev-util/gppg-dbremner'
    - 'dev-util/naive-language-tools'
    - 'app-crypt/mono-letsencrypt'
    - 'app-editors/mypad'
    - 'media-gfx/pinta'
    - 'dev-lang/oscript'

# no motivation to fix
#    - 'dev-lang/ironscheme'
#    - '<net-irc/smuxi-9000'

  equo:
    dependency_install:
      prune_virtuals: 1
