repository:
  description: Pantheon Desktop Repository
build:
  emerge:
    # Install each package separately
    split_install: 1
    features: assume-digests binpkg-logs -collision-detect compressdebug config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync news parallel-fetch preserve-libs -protect-owned -sandbox sfperms splitdebug strict unknown-features-warn unmerge-logs unmerge-orphans userfetch usersandbox usersync xattr -userpriv
    remote_overlay:
      - sabayon|git|https://github.com/Sabayon/for-gentoo.git
  overlays:
    - elementary
    - gnome-next
  target:
    - dev-lang/vala::gnome-next
    - pantheon-base/cerbere::elementary
    - pantheon-base/pantheon::elementary
    - pantheon-base/pantheon-files::elementary
    - pantheon-base/pantheon-greeter::elementary
    - pantheon-base/pantheon-settings::elementary
    - pantheon-base/pantheon-shell[-lightdm,-screensaver]::elementary
    - pantheon-base/plank::elementary
    - pantheon-base/screenshot-tool::elementary
    - pantheon-base/slingshot::elementary
    - pantheon-base/switchboard::elementary
    - pantheon-base/switchboard-plug-about::elementary
    - pantheon-base/switchboard-plug-accessibility::elementary
    - pantheon-base/switchboard-plug-applications::elementary
    - pantheon-base/switchboard-plug-bluetooth::elementary
    - pantheon-base/switchboard-plug-datetime::elementary
    - pantheon-base/switchboard-plug-display::elementary
    - pantheon-base/switchboard-plug-keyboard::elementary
    - pantheon-base/switchboard-plug-locale::elementary
    - pantheon-base/switchboard-plug-mouse-touchpad::elementary
    - pantheon-base/switchboard-plug-network::elementary
    - pantheon-base/switchboard-plug-notifications::elementary
    - pantheon-base/switchboard-plug-onlineaccounts::elementary
    - pantheon-base/switchboard-plug-pantheon-shell::elementary
    - pantheon-base/switchboard-plug-parental-controls::elementary
    - pantheon-base/switchboard-plug-power::elementary
    - pantheon-base/switchboard-plug-printers::elementary
    - pantheon-base/switchboard-plug-security-privacy::elementary
    - pantheon-base/switchboard-plug-sharing::elementary
    - pantheon-base/switchboard-plug-useraccounts::elementary
    - pantheon-base/wingpanel::elementary
    - pantheon-base/wingpanel-indicator-bluetooth::elementary
    - pantheon-base/wingpanel-indicator-datetime::elementary
    - pantheon-base/wingpanel-indicator-keyboard::elementary
    - pantheon-base/wingpanel-indicator-network::elementary
    - pantheon-base/wingpanel-indicator-notifications::elementary
    - pantheon-base/wingpanel-indicator-power::elementary
    - pantheon-base/wingpanel-indicator-session::elementary
    - pantheon-base/wingpanel-indicator-sound::elementary
    - x11-wm/gala::elementary
