repository:
   description: Sabayon Community SCR
build:
  emerge:
    # Install each package separately
    split_install: 1
    preserved_rebuild: 1
    remote_overlay:
       - flatpak-overlay|git|https://github.com/fosero/flatpak-overlay.git
       - fsociety|git|https://github.com/z1lt0id/fs0ciety.git
       - np-hardass-overlay|git|https://github.com/NP-Hardass/np-hardass-overlay.git
       - sabayon-community|git|https://github.com/Sabayon/community.git
       - tlp|git|https://github.com/dywisor/tlp-portage.git
  overlays:
    - 4nykey
    - activehome
    - and3k-sunrise
    - angelos
    - anyc
    - axs
    - belak
    - bobwya
    - brother-overlay
    - c2p-overlay
    - cynede
    - Drauthius
    - didactic-duck
    - dlang
    - dev-zero
    - ephemeral
    - eva
    - fkmclane
    - flavour
    - furikake
    - fuverlay
    - gamerlay
    - games-overlay
    - gentoo-htpc
    - genealogy
    - go-overlay
    - graaff
    - hamper-overlay
    - ikelos
    - jorgicio
    - jtriley
    - k_f
    - lmiphay
    - miramir
    - mozilla
    - mrueg
    - ohnobinki_overlay
    - pentoo
    - poly-c
    - rasdark
    - robbat2
    - ROKO__
    - roslin
    - salfter
    - sk-overlay
    - sinustrom
    - Spring
    - ssnb
    - steam-overlay
    - stefantalpalaru
    - sublime-text
    - swegener
    - TAJJADA
    - tmacedo
    - trash
    - voyageur
    - weuxel
    - y2kbadbug
    - zugaina
  equo:
    package:
      install:
        - dev-libs/ocl-icd
  target:
    - app-arch/peazip::c2p-overlay
    - app-arch/rarcrack::robbat2
    - app-crypt/veracrypt
    - app-dicts/artha
    - app-editors/atom-bin::jorgicio
    - app-editors/gedit-latex::eva
    - app-editors/scribes::belak
    - app-editors/sublime-text::sublime-text
    - app-emulation/genymotion
    - app-emulation/RemoteBox::gentoo-htpc
    - app-emulation/shashlik-bin::anyc
    - app-eselect/eselect-sublime::sublime-text
    - app-laptop/tlp
    - app-misc/anki::sk-overlay
    - app-misc/double-commander
    - app-misc/fet::LocalOverlay
    - app-misc/gramps::genealogy
    - app-misc/neofetch::fsociety
    - app-office/archi::flavour
    - app-office/jstock::sinustrom
    - app-office/onlyoffice::jorgicio
    - app-text/cherrytree::and3k-sunrise
    - app-text/gimagereader::salfter
    - app-text/gist::sk-overlay
    - dev-embedded/arduino::TAJJADA
    - dev-embedded/arduino-ide::TAJJADA
    - dev-embedded/stlink::swegener
    - dev-lang/haxe
    - =dev-libs/intel-beignet-9999::mrueg
    - dev-tex/mimetex::k_f
    - dev-util/adobe-air-runtime::steam-overlay
    - dev-util/eclipse-sdk-bin::jorgicio
    - dev-util/flatpak-builder::flatpak-overlay
    - dev-util/idea-community::ssnb
    - dev-util/phpstorm
    - dev-util/pycharm-community
    - dev-util/pycharm-professional
    - games-arcade/fretsonfire
    - games-arcade/mars-bin
    - games-arcade/mars-game::gamerlay
    - games-arcade/sdl-ball::roslin
    - games-fps/redeclipse::gamerlay
    - games-puzzle/osmos::gamerlay
    - games-sports/maniadrive-bin::zugaina
    - games-strategy/megaglest::games-overlay
    - games-strategy/unknown-horizons::gamerlay
    - games-strategy/zod-engine::games-overlay
    - games-util/fteqcc-xonotic-9999::gamerlay
    - games-util/springlobby::Spring
    - games-util/wiithon::LocalOverlay
    - gnome-extra/gnome-encfs::ephemeral
    - kde-misc/nowdock-panel::lmiphay
    - media-gfx/brother-dcp145c-bin::brother-overlay
    - media-gfx/font-manager::sk-overlay
    - media-gfx/lightzone
    - media-gfx/phatch::jtriley
    - media-gfx/pinta
    - media-gfx/Slic3r-bin::axs
    - media-gfx/sweethome3d-bin::activehome
    - media-gfx/ttfautohint::4nykey
    - media-sound/guitarix2::jorgicio
    - media-sound/lollypop::jorgicio
    - media-sound/nuvolaplayer::furikake
    - media-sound/pulseaudio-equalizer::zyrenth
    - media-sound/pulseeffects
    - media-sound/vkaudiosaver::ROKO__
    - media-tv/peerflix::jorgicio
    - media-tv/plex-media-server
    - media-video/filebot
    - media-video/flowblade
    - net-im/hipchat::tmacedo
    - net-im/qtox-bin
    - net-im/skypeforlinux
    - net-im/slack::lmiphay
    - net-im/telegram-bin::fuverlay
    - net-im/zoom-bin::yurij-overlay
    - net-mail/davmail-bin::pentoo
    - net-misc/megasync::jorgicio
    - net-misc/miraclecast::angelos
    - =net-misc/gopenvpn-9999::np-hardass-overlay
    - net-misc/cjdns::weuxel
    - net-misc/streamtuner2::stefantalpalaru
    - net-print/brother-genml1-bin::brother-overlay
    - net-print/cloudprint::dev-zero
    - net-print/samsung-unified-linux-driver::ohnobinki_overlay
    - sci-geosciences/googleearth::voyageur
    - sys-apps/flatpak::flatpak-overlay
    - sys-apps/sift::go-overlay
    - sys-app/xdg-desktop-portal::flatpak-overlay
    - sys-app/xdg-desktop-portal-gtk::flatpak-overlay
    - sys-cluster/kubectl
    - sys-fs/ostree::flatpak-overlay
    - sys-fs/zfstools::graaff
    - www-apps/hugo::go-overlay
    - www-client/palemoon::palemoon
    - x11-apps/disper::trash
    - x11-drivers/wizardpen::jorgicio
    - x11-libs/libvdpau-va-gl::sk-overlay
    - x11-misc/iio-sensor-proxy
    - x11-misc/mugshot::y2kbadbug
    - x11-terms/altyo
    - x11-terms/tilix::dlang
    - x11-wm/lumina::poly-c
