repository:
   description: Sabayon Community SCR
build:
  emerge:
    # Install each package separately
    split_install: 1
    remote_overlay:
       - bgo-overlay|rsync|rsync://gentoo.zugaina.org/bgo-overlay
       - fsociety|git|https://github.com/z1lt0id/fs0ciety.git
       - np-hardass-overlay|git|https://github.com/NP-Hardass/np-hardass-overlay.git
       - sabayon-community|git|https://github.com/Sabayon/community.git
  overlays:
    - activehome
    - and3k-sunrise
    - angelos
    - anyc
    - Armageddon
    - axs
    - belak
    - c2p-overlay
    - dev-zero
    - ephemeral
    - eva
    - flavour
    - furikake
    - fuverlay
    - gamerlay
    - games-overlay
    - gentoo-htpc
    - go-overlay
    - graaff
    - hossie
    - jorgicio
    - jtriley
    - k_f
    - lmiphay
    - mozilla
    - mrueg
    - nikai
    - ohnobinki_overlay
    - pentoo
    - robbat2
    - ROKO__
    - roslin
    - sinustrom
    - Spring
    - steam-overlay
    - stefantalpalaru
    - sublime-text
    - sunrise
    - swegener
    - TAJJADA
    - tmacedo
    - weuxel
    - y2kbadbug
    - zugaina
  equo:
    package:
      install:
        - dev-libs/ocl-icd
  target:
    - app-admin/cpu-g::sunrise
    - app-arch/peazip::c2p-overlay
    - app-arch/rarcrack::robbat2
    - app-dicts/artha
    - app-editors/gedit-latex::eva
    - app-editors/scribes::belak
    - app-editors/sublime-text::sublime-text
    - app-emulation/genymotion
    - app-emulation/RemoteBox::gentoo-htpc
    - app-emulation/shashlik-bin::anyc
    - app-eselect/eselect-sublime::sublime-text
    - app-i18n/virtaal::bgo-overlay
    - app-misc/fet
    - app-misc/neofetch::fsociety
    - app-office/archi::flavour
    - app-office/jstock::sinustrom
    - app-text/cherrytree::and3k-sunrise
    - app-text/voikko
    - dev-embedded/arduino::TAJJADA
    - dev-embedded/arduino-ide::TAJJADA
    - dev-embedded/stlink::swegener
    - dev-libs/intel-beignet::mrueg
    - dev-tex/mimetex::k_f
    - dev-util/adobe-air-runtime::steam-overlay
    - dev-util/eclipse-sdk-bin::jorgicio
    - dev-util/idea-community::hossie
    - games-action/meritous::sunrise
    - games-arcade/sdl-ball::roslin
    - games-fps/redeclipse::gamerlay
    - games-puzzle/osmos::gamerlay
    - =games-simulation/vegastrike-data-9999::LocalOverlay
    - =games-simulation/vegastrike-9999::nikai
    - games-sports/maniadrive-bin::zugaina
    - games-strategy/megaglest::games-overlay
    - games-strategy/unknown-horizons::gamerlay
    - games-strategy/zod-engine::games-overlay
    - games-util/springlobby::Spring
    - gnome-extra/gnome-encfs::ephemeral
    - media-gfx/lightzone
    - media-gfx/phatch::jtriley
    - media-gfx/Slic3r-bin::axs
    - media-gfx/sweethome3d-bin::activehome
    - media-gfx/yed::c2p-overlay
    - media-gfx/xaralx::sunrise
    - media-sound/guitarix2::jorgicio
    - media-sound/nuvolaplayer::furikake
    - media-sound/vkaudiosaver::ROKO__
    - media-tv/peerflix::jorgicio
    - media-video/flowblade::Armageddon
    - net-im/hipchat::tmacedo
    - net-im/qtox-bin
    - net-im/slack::lmiphay
    - net-im/telegram-bin::fuverlay
    - net-mail/davmail-bin::pentoo
    - net-misc/megasync::jorgicio
    - net-misc/miraclecast::angelos
    - =net-misc/gopenvpn-9999::np-hardass-overlay
    - net-misc/cjdns::weuxel
    - net-misc/streamtuner2::stefantalpalaru
    - net-print/cloudprint::dev-zero
    - net-print/samsung-unified-linux-driver::ohnobinki_overlay
    - sys-apps/sift::go-overlay
    - sys-fs/zfstools::graaff
    - www-apps/hugo::go-overlay
    - x11-drivers/wizardpen::jorgicio
    - x11-misc/mugshot::y2kbadbug
    - x11-terms/altyo
