repository:
   description: Rust repository
   maintenance:

build:

  equo:
    repository: weekly

  emerge:
    remote_overlay:
      - sabayon|git|https://github.com/Sabayon/for-gentoo.git

  overlays:
    - rust

  target:
    - app-portage/cargo-ebuild

