repository:
   description: Kernel Devel
build:
  qa_checks: 0
  emerge:
    # Install each package separately
    split_install: 1
    default_args: --accept-properties=-interactive -t --verbose --nospinner --oneshot --complete-graph --buildpkg
    features: assume-digests binpkg-logs -userpriv config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync parallel-fetch preserve-libs protect-owned sandbox sfperms splitdebug strict
  target:
    - sys-kernel/linux-sabayon[dracut]
    - net-vpn/wireguard
    - app-emulation/virtualbox-modules
    - sys-power/bbswitch
    - sys-power/acpi_callsys-power/acpi_call
    - sys-fs/vhba
    - net-wireless/broadcom-sta
    - net-firewall/rtsp-conntrack
    - net-firewall/xtables-addons
    - media-video/v4l2loopback
    - app-laptop/tp_smapi-0.43
    - app-emulation/virtualbox-guest-additions
    - x11-drivers/nvidia-drivers
    - sys-kernel/spl::gentoo
    - sys-fs/zfs-kmod::gentoo
    - sys-fs/zfs::gentoo
