repository:
   description: ZFS Repository

build:
  script:
    pre:
      - eselect kernel set linux-5.0.0-sabayon
      - kernel-switcher switch linux-sabayon:5.0

  qa_checks: 1

  emerge:
    split_install: 1
    default_args: "--accept-properties=-interactive -t --nospinner --oneshot --complete-graph --buildpkg --newuse"
    jobs: 2

  equo:
      package:
          # Prevent conflicts between zfs-0.7 with split spl, versus 0.8 with bundled spl
          remove:
              - sys-kernel/spl
              - "=sys-fs/zfs-0.7.13"
              - "=sys-fs/zfs-kmod-0.7.13"
          mask:
              - sys-kernel/spl
              - "<sys-fs/zfs-0.8.0"
              - "<sys-fs/zfs-kmod-0.8.0"
  
  target:
    - sys-fs/zfs
    - sys-fs/zfs-kmod

