repository:
   description: kdepim repository
build:
  target:
    - kde-apps/kdepim-meta
  equo:
    package:
      install:
        - app-crypt/pinentry
  emerge:
    features: splitdebug
    remove:
      - kde-apps/kmail:4
      - kde-apps/korganizer:4
      - kde-apps/kalarm:4
      - kde-apps/akregator:4
      - kde-apps/kdepim-runtime:4
      - kde-apps/kaddressbook:4
      - app-office/akonadi-server
      - kde-apps/calendarjanitor:4
      - kde-apps/ktnef:4
      - kde-apps/kontact:4
      - kde-apps/akonadiconsole:4
      - kde-apps/kdepimlibs:4
      - kde-apps/kdepim-common-libs:4
      - kde-apps/blogilo:4
      - kde-apps/konsolekalendar:4
      - kde-base/baloo:4
      - dev-libs/xapian
      - kde-apps/kde-l10n
