repository:
   description: Gaming live repository
   maintenance:
     clean_cache: 1
build:
  emerge:
    # Install each package separately
    split_install: 1
    default_args: --accept-properties=-interactive -t --verbose --nospinner --oneshot --complete-graph --buildpkg
    features: assume-digests binpkg-logs -userpriv config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync parallel-fetch preserve-libs protect-owned sandbox sfperms splitdebug strict
    remote_overlay:
      - sabayon|git|https://github.com/Sabayon/for-gentoo.git
  overlays:
  target:
    - =dev-util/meson-9999
    - =sys-devel/clang-9999[doc]::gentoo
    - =sys-devel/clang-runtime-9999::gentoo
    - =sys-libs/libomp-9999::gentoo
    - =sys-libs/compiler-rt-9999::gentoo
    - =sys-libs/compiler-rt-sanitizers-9999::gentoo
    - =sys-devel/llvm-9999[doc]::gentoo
    - =media-libs/mesa-9999::gentoo
