repository:
  description: Sihnon common packages

  maintenance:
    keep_previous_versions: 1
    clean_cache: 1

build:
  emerge:
    # Install each package separately
    split_install: 1
    preserved_rebuild: 1

    remote_overlay:
      - sabayon|git|https://github.com/Sabayon/for-gentoo.git

  # Use ebuilds from the following layman overlays
  overlays:
    - ace
    - sihnon

  # Packages to be built in this repo
  target:
    - app-admin/puppet-env-manager::sihnon
    - app-crypt/dehydrated::gentoo
    - app-admin/consul::gentoo
    - app-admin/lastpass-cli::gentoo
    - app-admin/vault::gentoo
    - app-vim/puppet-syntax::gentoo
    - dev-perl/Monitoring-Plugin::gentoo
    - dev-python/django-haystack::gentoo
    - dev-python/py-mco-agent::sihnon
    - dev-vcs/vcsh::gentoo
    - net-analyzer/nagios-plugins::gentoo
    - net-analyzer/nagios-plugin-check-scsi-smart::sihnon
    - net-dns/hash-slinger::gentoo
    - net-misc/choria-bin::ace
    - net-misc/lldpd::gentoo
    - net-misc/openssh::gentoo
    - net-misc/pssh::gentoo
    - sys-auth/sssd::gentoo
    - sys-fs/zfs-auto-snapshot::gentoo

# vim: set ts=2 shiftwidth=2 expandtab :
