repository:
  description: Sihnon desktop packages

  # 2016-09-14 temporarily start clean
  #maintenance:
  #  clean_cache: 1

  remove:
      # Available in sabayonlinux.org
    - sys-auth/ykpers

build:
  script:
    pre:
      - eselect python set python3.6
      - eselect ruby set ruby24

  emerge:
    # Be consistent with sabayon mainline repositories
    profile: "default/linux/amd64/17.0/desktop"

    # Install each package separately
    split_install: 1
    preserved_rebuild: 1

    remote_overlay:
      - sabayon|git|https://github.com/Sabayon/for-gentoo.git

  # Use ebuilds from the following layman overlays
  overlays:
    - jkolo
    - sihnon

  # Packages to be built in this repo
  target:
    - app-crypt/yubico-piv-tool
    - app-crypt/yubikey-neo-manager
    - app-crypt/yubikey-piv-manager

# vim: set ts=2 shiftwidth=2 expandtab :
